networks:
  emoncms_legacy:
    name: emoncms_legacy
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"
          gateway: "172.22.0.1"

services:

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=emoncms
    volumes:
      - emon-db-data:/var/lib/mysql
    networks:
      - emoncms_legacy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - emoncms_legacy

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - /emoncms_conf/mosquitto/config:/mosquitto/config
    ports:
      - 2883:1883
    networks:
      - emoncms_legacy

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - emoncms_legacy

  web:
    image: openenergymonitor/emoncms:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=emoncms
      - MYSQL_PASSWORD=emonpiemoncmsmysql2016
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PREFIX='emoncms'
      - MQTT_ENABLED=true
      - MQTT_HOST=mqtt
      - MQTT_CLIENTID=emoncmsmqtt
      - MQTT_USER=emonpi
      - MQTT_PASSWORD=emonpimqtt2016
      - MQTT_BASETOPIC=emon
      - MQTT_PORT=1883
      - PHPFINA_DIR=/var/opt/emoncms/phpfina/
      - PHPTIMESERIES_DIR=/var/opt/emoncms/phptimeseries/
    volumes:
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
    networks:
      - emoncms_legacy


volumes:
  emon-phpfina:
  emon-phptimeseries:
  emon-db-data:
